language: node_js
node_js:
  - '8'
before_install:
  - npm i -g npm@v8.12.0
cache:
  directories:
    - 'node_modules'
services:
  - postgresql
before_script:
  - psql -c 'create database travis_test;' -U postgres
